/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRankingsRouteImport } from './routes/_app/rankings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNewNightRouteImport } from './routes/_app/new-night'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppFriendsRouteImport } from './routes/_app/friends'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppUIdRouteImport } from './routes/_app/u.$id'
import { Route as AppNightIdRouteImport } from './routes/_app/night.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNewNightRoute = AppNewNightRouteImport.update({
  id: '/new-night',
  path: '/new-night',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppUIdRoute = AppUIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNightIdRoute = AppNightIdRouteImport.update({
  id: '/night/$id',
  path: '/night/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRoute
  '/friends': typeof AppFriendsRoute
  '/map': typeof AppMapRoute
  '/new-night': typeof AppNewNightRoute
  '/profile': typeof AppProfileRoute
  '/rankings': typeof AppRankingsRoute
  '/night/$id': typeof AppNightIdRoute
  '/u/$id': typeof AppUIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRoute
  '/friends': typeof AppFriendsRoute
  '/map': typeof AppMapRoute
  '/new-night': typeof AppNewNightRoute
  '/profile': typeof AppProfileRoute
  '/rankings': typeof AppRankingsRoute
  '/night/$id': typeof AppNightIdRoute
  '/u/$id': typeof AppUIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/map': typeof AppMapRoute
  '/_app/new-night': typeof AppNewNightRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rankings': typeof AppRankingsRoute
  '/_app/night/$id': typeof AppNightIdRoute
  '/_app/u/$id': typeof AppUIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/feed'
    | '/friends'
    | '/map'
    | '/new-night'
    | '/profile'
    | '/rankings'
    | '/night/$id'
    | '/u/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/feed'
    | '/friends'
    | '/map'
    | '/new-night'
    | '/profile'
    | '/rankings'
    | '/night/$id'
    | '/u/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/feed'
    | '/_app/friends'
    | '/_app/map'
    | '/_app/new-night'
    | '/_app/profile'
    | '/_app/rankings'
    | '/_app/night/$id'
    | '/_app/u/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rankings': {
      id: '/_app/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-night': {
      id: '/_app/new-night'
      path: '/new-night'
      fullPath: '/new-night'
      preLoaderRoute: typeof AppNewNightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/u/$id': {
      id: '/_app/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof AppUIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/night/$id': {
      id: '/_app/night/$id'
      path: '/night/$id'
      fullPath: '/night/$id'
      preLoaderRoute: typeof AppNightIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedRoute: typeof AppFeedRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppMapRoute: typeof AppMapRoute
  AppNewNightRoute: typeof AppNewNightRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRankingsRoute: typeof AppRankingsRoute
  AppNightIdRoute: typeof AppNightIdRoute
  AppUIdRoute: typeof AppUIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFeedRoute: AppFeedRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppMapRoute: AppMapRoute,
  AppNewNightRoute: AppNewNightRoute,
  AppProfileRoute: AppProfileRoute,
  AppRankingsRoute: AppRankingsRoute,
  AppNightIdRoute: AppNightIdRoute,
  AppUIdRoute: AppUIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
